[package]
name = "numext-fixed-uint"
version = "0.1.0"
authors = ["Boyu Yang <yangby@cryptape.com>"]

[dependencies]
numext-fixed-uint-macros = { path = "../fixed-uint-macros" }
failure = "0.1"
rand = { version = "0.5", optional = true }

[features]
default = []
impl_rand = ["rand", "numext-fixed-uint-macros/rand"]
