[package]
name = "numext-fixed-uint"
version = "0.1.0"
authors = ["Boyu Yang <yangby@cryptape.com>"]

[dependencies]
numext-constructor = { path = "../constructor" }
failure = "0.1"
rand = { version = "0.5", optional = true }
heapsize = { version = "0.4", optional = true }
serde = { version = "1.0", optional = true }
faster-hex = { version = "0.1.0", optional = true }

[features]
default = []
impl_rand = ["rand", "numext-constructor/rand"]
impl_heapsize = ["heapsize", "numext-constructor/heapsize"]
impl_serde = ["serde", "faster-hex", "numext-constructor/serde"]
