[package]
name = "numext-fixed-uint"
version = "0.1.0"
authors = [
    "Boyu Yang <yangby@cryptape.com>",
    "zhangsoledad <787953403@qq.com>",
]

[dependencies]
numext-constructor = { path = "../constructor" }
failure = "0.1"
rand = { version = "0.5", optional = true }
heapsize = { version = "0.4", optional = true }
serde = { version = "1.0", optional = true }
faster-hex = { version = "0.1", optional = true }

[features]
default = []
support_all = ["support_rand", "support_heapsize", "support_serde"]
support_rand = ["rand"]
support_heapsize = ["heapsize"]
support_serde = ["serde", "faster-hex"]
