[package]
name = "numext-fixed-uint"
version = "0.1.0"
authors = ["Boyu Yang <yangby@cryptape.com>"]

[dependencies]
numext-fixed-uint-macros = { path = "../fixed-uint-macros" }
failure = "0.1"
rand = "0.5"

[features]
default = []
