[package]
name = "nfhash_tests"
version = "0.1.0"
authors = [
    "Boyu Yang <yangby@cryptape.com>",
    "zhangsoledad <787953403@qq.com>",
]
edition = "2018"
autobenches = false

[dependencies]
nfhash = { path = "../fixed-hash", features = ["support_all"], package = "numext-fixed-hash" }
etypes = { version = "0.4", package = "ethereum-types" }
proptest = "0.8"
rand = "0.5"

[dev-dependencies]
criterion = "0.2"
serde_json = "1.0"


[[bench]]
name = "ext_serde"
harness = false
