[package]
name = "numext-fixed-hash-tests"
version = "0.1.0"
authors = [
    "Boyu Yang <yangby@cryptape.com>",
    "zhangsoledad <787953403@qq.com>",
]
autobenches = false

[dependencies]
numext-fixed-hash = { path = "../fixed-hash", features = ["support_all"] }
ethereum-types = "0.4"
proptest = "0.8"
rand = "0.5"

[dev-dependencies]
criterion = "0.2"
serde_json = "1.0"
